server:
  port: 8081 # Gateway(8000), Eureka(8761)과 겹치지 않게 설정

spring:
  application:
    name: monitoring-service
  
  datasource:
    # ClickHouse 연결 정보 (IP, Port, DB명 확인 필요)
    url: jdbc:clickhouse://localhost:8123/van_db?compress=0
    username: default # ClickHouse 기본 계정 (설정에 따라 변경)
    password:         # 패스워드가 있다면 입력
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  jpa:
    hibernate:
      ddl-auto: none # 중요! ClickHouse는 스키마 자동 생성을 끕니다.
    show-sql: true   # 실행되는 쿼리를 로그로 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/