server:
  port: 8081 # Gateway(8000), Eureka(8761)과 겹치지 않게 설정

spring:
  application:
    name: monitoring-service
  config:
    import: "optional:configserver:http://localhost:8888/"

management:
  endpoints:
    web:
      exposure:
        include: refresh

# Jasypt 설정 (복호화 키는 실행 시 주입받으므로 빈 값으로 둡니다)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor # (선택) 커스텀 빈 사용 시
    algorithm: PBEWITHHMACSHA512ANDAES_256

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/